site_name: D&A
site_author: "Brother Rain"
google_analytics: ['UA-68978617-1', 'magizbox.com']

pages:
- "Home": 'index.md'
- "Data Structures":
  - "Arrays": 'd_array.md'
  - "Strings": 'd_string.md'
  - "Stacks & Queues": 'd_stack_queue.md'
  - "Trees": 'd_tree.md'
  - "Heaps": 'd_heap.md'
  - "Tries": 'd_trie.md'
- "Algorithms":
  - "7 Steps to Solve Algorithm Problems": "7_steps.md"
  - "Graph Theory": 'a_graph_theory.md'

markdown_extensions:
    - footnotes
    - mdx_math

extra_css:
  - css/book.css
  - css/course.css
  - css/video.css
extra_javascript:
  - js/underscore.js
  - js/gspreadsheet.js
  - js/book.js
  - js/course.js
  - js/video.js
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

